import { DriverRoute, PassengerRequest } from '../../types';
import { interpolatePolyline } from '../routing/geometry';
import { VIETNAM_LOCATIONS } from '../routing/routingProvider';

export const INITIAL_DRIVERS: DriverRoute[] = [
  {
    id: 'DRV_01',
    driverId: 'D01',
    driver: {
      id: 'D01',
      name: 'Nguyễn Văn An',
      phone: '0912 345 678',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      rating: 4.95,
      totalTrips: 342,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 98,
    },
    origin: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    destination: VIETNAM_LOCATIONS.NB_CENTRAL,
    departureWindow: {
      start: '08:00',
      end: '08:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V01',
      model: 'Toyota Innova Cross 2024',
      licensePlate: '29A-888.36',
      color: 'Trắng Ngọc Trai',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Không gian yên tĩnh', 'Cốp rộng', 'Điều hòa 2 vùng độc lập', 'Nước suối miễn phí'],
    },
    occupiedSeats: 5,
    availableSeats: 2,
    basePricePerSeat: 180000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: ['PR_SEED_01', 'PR_SEED_02'],
    waypoints: [
      { id: 'wp-orig-1', name: 'Bến xe Giáp Bát, Hà Nội', coords: VIETNAM_LOCATIONS.HN_GIAP_BAT.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-1', name: 'Nút giao Liêm Tuyền (Phủ Lý)', coords: VIETNAM_LOCATIONS.HNAM_PHU_LY.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-dest-1', name: 'TP. Ninh Bình', coords: VIETNAM_LOCATIONS.NB_CENTRAL.coords, type: 'destination', order: 2 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_GIAP_BAT.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_DONG_VAN.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.ND_Y_YEN.coords,
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
    ], 6),
  },

  {
    id: 'DRV_02',
    driverId: 'D02',
    driver: {
      id: 'D02',
      name: 'Trần Quốc Tuấn',
      phone: '0988 123 456',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      rating: 4.91,
      totalTrips: 215,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 96,
    },
    origin: VIETNAM_LOCATIONS.HN_HOAN_KIEM,
    destination: VIETNAM_LOCATIONS.NB_TRANG_AN,
    departureWindow: {
      start: '08:15',
      end: '08:45',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V02',
      model: 'Hyundai Staria VIP Limousine',
      licensePlate: '30E-666.99',
      color: 'Đen Sang Trọng',
      type: '9_seats',
      totalSeats: 9,
      features: ['Không hút thuốc', 'Ghế thương gia massage', 'Wifi 5G', 'Sạc Type-C từng ghế', 'Cốp siêu rộng'],
    },
    occupiedSeats: 6,
    availableSeats: 3,
    basePricePerSeat: 220000,
    corridorWidthKm: 2.5,
    status: 'scheduled',
    matchedPassengerIds: ['PR_SEED_03'],
    waypoints: [
      { id: 'wp-orig-2', name: 'Bờ Hồ Hoàn Kiếm, Hà Nội', coords: VIETNAM_LOCATIONS.HN_HOAN_KIEM.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-2a', name: 'Bến xe Nước Ngầm', coords: VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-stop-2b', name: 'Nút giao Liêm Tuyền', coords: VIETNAM_LOCATIONS.HNAM_PHU_LY.coords, type: 'corridor_stop', order: 2 },
      { id: 'wp-dest-2', name: 'KDL Tràng An, Ninh Bình', coords: VIETNAM_LOCATIONS.NB_TRANG_AN.coords, type: 'destination', order: 3 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_HOAN_KIEM.coords,
      VIETNAM_LOCATIONS.HN_GIAP_BAT.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_DONG_VAN.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
      VIETNAM_LOCATIONS.NB_TRANG_AN.coords,
    ], 6),
  },

  {
    id: 'DRV_03',
    driverId: 'D03',
    driver: {
      id: 'D03',
      name: 'Lê Hoàng Long',
      phone: '0903 456 789',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      rating: 4.88,
      totalTrips: 180,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 94,
    },
    origin: VIETNAM_LOCATIONS.HN_MY_DINH,
    destination: VIETNAM_LOCATIONS.NB_CENTRAL,
    departureWindow: {
      start: '08:30',
      end: '09:00',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V03',
      model: 'Mitsubishi Xpander Premium',
      licensePlate: '29H-789.12',
      color: 'Bạc Titan',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Cốp rộng', 'Cho phép thú cưng', 'Điều hòa mát sâu'],
    },
    occupiedSeats: 4,
    availableSeats: 3,
    basePricePerSeat: 170000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-3', name: 'Bến xe Mỹ Đình, Hà Nội', coords: VIETNAM_LOCATIONS.HN_MY_DINH.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-3', name: 'Vành đai 3 - Pháp Vân', coords: VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-dest-3', name: 'TP. Ninh Bình', coords: VIETNAM_LOCATIONS.NB_CENTRAL.coords, type: 'destination', order: 2 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_MY_DINH.coords,
      VIETNAM_LOCATIONS.HN_HA_DONG.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.ND_Y_YEN.coords,
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
    ], 6),
  },

  {
    id: 'DRV_04',
    driverId: 'D04',
    driver: {
      id: 'D04',
      name: 'Phạm Văn Hùng',
      phone: '0977 888 999',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      rating: 4.96,
      totalTrips: 410,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 99,
    },
    origin: VIETNAM_LOCATIONS.HN_NUOC_NGAM,
    destination: VIETNAM_LOCATIONS.TH_CENTRAL,
    departureWindow: {
      start: '08:00',
      end: '08:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V04',
      model: 'Toyota Fortuner Legender',
      licensePlate: '36A-555.88',
      color: 'Đen Mờ',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Gầm cao êm ái', 'Cốp rộng', 'Nước uống & khăn lạnh'],
    },
    occupiedSeats: 4,
    availableSeats: 3,
    basePricePerSeat: 190000,
    corridorWidthKm: 3.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-4', name: 'Bến xe Nước Ngầm, Hà Nội', coords: VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-4a', name: 'Nút giao Liêm Tuyền (Phủ Lý)', coords: VIETNAM_LOCATIONS.HNAM_PHU_LY.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-stop-4b', name: 'Nút giao Cao Bồ (Ninh Bình)', coords: VIETNAM_LOCATIONS.NB_CENTRAL.coords, type: 'corridor_stop', order: 2 },
      { id: 'wp-dest-4', name: 'TP. Thanh Hóa', coords: VIETNAM_LOCATIONS.TH_CENTRAL.coords, type: 'destination', order: 3 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
      VIETNAM_LOCATIONS.NB_TAM_DIEP.coords,
      VIETNAM_LOCATIONS.TH_CENTRAL.coords,
    ], 6),
  },

  {
    id: 'DRV_05',
    driverId: 'D05',
    driver: {
      id: 'D05',
      name: 'Vũ Minh Đức',
      phone: '0966 222 333',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      rating: 4.89,
      totalTrips: 156,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 92,
    },
    origin: VIETNAM_LOCATIONS.HN_HOAN_KIEM,
    destination: VIETNAM_LOCATIONS.ND_CENTRAL,
    departureWindow: {
      start: '09:00',
      end: '09:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V05',
      model: 'Kia Carnival Signature 2024',
      licensePlate: '18A-333.66',
      color: 'Xanh Đen',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Cửa trượt điện', 'Ghế đệm chỉnh điện', 'Không gian yên tĩnh'],
    },
    occupiedSeats: 3,
    availableSeats: 4,
    basePricePerSeat: 190000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-5', name: 'Bờ Hồ Hoàn Kiếm, Hà Nội', coords: VIETNAM_LOCATIONS.HN_HOAN_KIEM.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-5', name: 'Phủ Lý (Hà Nam)', coords: VIETNAM_LOCATIONS.HNAM_PHU_LY.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-dest-5', name: 'TP. Nam Định', coords: VIETNAM_LOCATIONS.ND_CENTRAL.coords, type: 'destination', order: 2 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_HOAN_KIEM.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.ND_BIG_C.coords,
      VIETNAM_LOCATIONS.ND_CENTRAL.coords,
    ], 6),
  },

  {
    id: 'DRV_06',
    driverId: 'D06',
    driver: {
      id: 'D06',
      name: 'Đặng Anh Tuấn',
      phone: '0934 567 890',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      rating: 4.85,
      totalTrips: 98,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 90,
    },
    origin: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    destination: VIETNAM_LOCATIONS.HNAM_PHU_LY,
    departureWindow: {
      start: '08:00',
      end: '08:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V06',
      model: 'Ford Everest Titanium',
      licensePlate: '90A-123.45',
      color: 'Nâu Ánh Kim',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Cốp rộng'],
    },
    occupiedSeats: 5,
    availableSeats: 2,
    basePricePerSeat: 120000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-6', name: 'Bến xe Giáp Bát', coords: VIETNAM_LOCATIONS.HN_GIAP_BAT.coords, type: 'origin', order: 0 },
      { id: 'wp-dest-6', name: 'Phủ Lý, Hà Nam', coords: VIETNAM_LOCATIONS.HNAM_PHU_LY.coords, type: 'destination', order: 1 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_GIAP_BAT.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_DONG_VAN.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
    ], 6),
  },

  {
    id: 'DRV_07',
    driverId: 'D07',
    driver: {
      id: 'D07',
      name: 'Đỗ Thành Nam',
      phone: '0915 999 111',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      rating: 4.78,
      totalTrips: 84,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 88,
    },
    origin: VIETNAM_LOCATIONS.HN_LONG_BIEN,
    destination: VIETNAM_LOCATIONS.HP_CENTRAL,
    departureWindow: {
      start: '08:00',
      end: '08:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V07',
      model: 'Toyota Vios G',
      licensePlate: '15A-456.78',
      color: 'Bạc',
      type: '4_seats',
      totalSeats: 4,
      features: ['Không hút thuốc'],
    },
    occupiedSeats: 2,
    availableSeats: 2,
    basePricePerSeat: 160000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-7', name: 'Aeon Mall Long Biên', coords: VIETNAM_LOCATIONS.HN_LONG_BIEN.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-7', name: 'Nút giao TP. Hải Dương', coords: VIETNAM_LOCATIONS.HD_CENTRAL.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-dest-7', name: 'TP. Hải Phòng', coords: VIETNAM_LOCATIONS.HP_CENTRAL.coords, type: 'destination', order: 2 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_LONG_BIEN.coords,
      VIETNAM_LOCATIONS.HD_CENTRAL.coords,
      VIETNAM_LOCATIONS.HP_VINCOM.coords,
      VIETNAM_LOCATIONS.HP_CENTRAL.coords,
    ], 6),
  },

  {
    id: 'DRV_08',
    driverId: 'D08',
    driver: {
      id: 'D08',
      name: 'Bùi Quang Huy',
      phone: '0981 777 666',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      rating: 4.92,
      totalTrips: 260,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 97,
    },
    origin: VIETNAM_LOCATIONS.HN_HOAN_KIEM,
    destination: VIETNAM_LOCATIONS.HP_VINCOM,
    departureWindow: {
      start: '09:00',
      end: '09:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V08',
      model: 'Hyundai SantaFe Calligraphy',
      licensePlate: '30K-999.88',
      color: 'Trắng Tuyết',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Không gian yên tĩnh', 'Cốp rộng', 'Loa Bose cao cấp'],
    },
    occupiedSeats: 4,
    availableSeats: 3,
    basePricePerSeat: 190000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-8', name: 'Hoàn Kiếm, Hà Nội', coords: VIETNAM_LOCATIONS.HN_HOAN_KIEM.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-8', name: 'TP. Hải Dương', coords: VIETNAM_LOCATIONS.HD_CENTRAL.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-dest-8', name: 'Vincom Hải Phòng', coords: VIETNAM_LOCATIONS.HP_VINCOM.coords, type: 'destination', order: 2 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_HOAN_KIEM.coords,
      VIETNAM_LOCATIONS.HN_LONG_BIEN.coords,
      VIETNAM_LOCATIONS.HD_CENTRAL.coords,
      VIETNAM_LOCATIONS.HP_VINCOM.coords,
    ], 6),
  },

  {
    id: 'DRV_09',
    driverId: 'D09',
    driver: {
      id: 'D09',
      name: 'Hoàng Trọng Nghĩa',
      phone: '0912 666 888',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      rating: 4.87,
      totalTrips: 130,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 91,
    },
    origin: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    destination: VIETNAM_LOCATIONS.NB_CENTRAL,
    departureWindow: {
      start: '14:00',
      end: '14:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V09',
      model: 'Kia Sedona Platinum',
      licensePlate: '29D-456.78',
      color: 'Ghi Bạc',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Cốp rộng', 'Điều hòa êm'],
    },
    occupiedSeats: 4,
    availableSeats: 3,
    basePricePerSeat: 180000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-9', name: 'Bến xe Giáp Bát', coords: VIETNAM_LOCATIONS.HN_GIAP_BAT.coords, type: 'origin', order: 0 },
      { id: 'wp-dest-9', name: 'TP. Ninh Bình', coords: VIETNAM_LOCATIONS.NB_CENTRAL.coords, type: 'destination', order: 1 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_GIAP_BAT.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
    ], 6),
  },

  {
    id: 'DRV_10',
    driverId: 'D10',
    driver: {
      id: 'D10',
      name: 'Nguyễn Hữu Thắng (Chiều Ngược)',
      phone: '0978 111 222',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      rating: 4.82,
      totalTrips: 75,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 89,
    },
    origin: VIETNAM_LOCATIONS.NB_CENTRAL,
    destination: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    departureWindow: {
      start: '08:00',
      end: '08:30',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V10',
      model: 'Mitsubishi Outlander',
      licensePlate: '35A-888.11',
      color: 'Đỏ Ruby',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc'],
    },
    occupiedSeats: 3,
    availableSeats: 4,
    basePricePerSeat: 170000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-10', name: 'TP. Ninh Bình', coords: VIETNAM_LOCATIONS.NB_CENTRAL.coords, type: 'origin', order: 0 },
      { id: 'wp-dest-10', name: 'Bến xe Giáp Bát, Hà Nội', coords: VIETNAM_LOCATIONS.HN_GIAP_BAT.coords, type: 'destination', order: 1 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HN_GIAP_BAT.coords,
    ], 6),
  },

  {
    id: 'DRV_11',
    driverId: 'D11',
    driver: {
      id: 'D11',
      name: 'Chu Đình Trọng',
      phone: '0904 333 444',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      rating: 4.93,
      totalTrips: 210,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 95,
    },
    origin: VIETNAM_LOCATIONS.HN_MY_DINH,
    destination: VIETNAM_LOCATIONS.NB_TAM_DIEP,
    departureWindow: {
      start: '08:15',
      end: '08:45',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V11',
      model: 'Toyota Veloz Cross',
      licensePlate: '29K-123.99',
      color: 'Trắng',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Cốp rộng', 'Sạc điện thoại'],
    },
    occupiedSeats: 5,
    availableSeats: 2,
    basePricePerSeat: 190000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-11', name: 'Mỹ Đình, Hà Nội', coords: VIETNAM_LOCATIONS.HN_MY_DINH.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-11', name: 'TP. Ninh Bình', coords: VIETNAM_LOCATIONS.NB_CENTRAL.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-dest-11', name: 'Tam Điệp, Ninh Bình', coords: VIETNAM_LOCATIONS.NB_TAM_DIEP.coords, type: 'destination', order: 2 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_MY_DINH.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
      VIETNAM_LOCATIONS.NB_TAM_DIEP.coords,
    ], 6),
  },

  {
    id: 'DRV_12',
    driverId: 'D12',
    driver: {
      id: 'D12',
      name: 'Mai Văn Cường',
      phone: '0945 888 777',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      rating: 4.90,
      totalTrips: 175,
      isIdentityVerified: true,
      isLicenseVerified: true,
      isVehicleVerified: true,
      trustScore: 93,
    },
    origin: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    destination: VIETNAM_LOCATIONS.TH_SAM_SON,
    departureWindow: {
      start: '07:45',
      end: '08:15',
      date: '2026-08-20',
    },
    vehicle: {
      id: 'V12',
      model: 'Isuzu Mu-X Premium',
      licensePlate: '36B-999.00',
      color: 'Xám Khói',
      type: '7_seats',
      totalSeats: 7,
      features: ['Không hút thuốc', 'Cốp siêu rộng', 'Ghế da êm ái'],
    },
    occupiedSeats: 6,
    availableSeats: 1,
    basePricePerSeat: 220000,
    corridorWidthKm: 2.0,
    status: 'scheduled',
    matchedPassengerIds: [],
    waypoints: [
      { id: 'wp-orig-12', name: 'Giáp Bát, Hà Nội', coords: VIETNAM_LOCATIONS.HN_GIAP_BAT.coords, type: 'origin', order: 0 },
      { id: 'wp-stop-12a', name: 'TP. Ninh Bình', coords: VIETNAM_LOCATIONS.NB_CENTRAL.coords, type: 'corridor_stop', order: 1 },
      { id: 'wp-stop-12b', name: 'TP. Thanh Hóa', coords: VIETNAM_LOCATIONS.TH_CENTRAL.coords, type: 'corridor_stop', order: 2 },
      { id: 'wp-dest-12', name: 'Biển Sầm Sơn', coords: VIETNAM_LOCATIONS.TH_SAM_SON.coords, type: 'destination', order: 3 },
    ],
    pathCoordinates: interpolatePolyline([
      VIETNAM_LOCATIONS.HN_GIAP_BAT.coords,
      VIETNAM_LOCATIONS.HN_NUOC_NGAM.coords,
      VIETNAM_LOCATIONS.HNAM_PHU_LY.coords,
      VIETNAM_LOCATIONS.NB_CENTRAL.coords,
      VIETNAM_LOCATIONS.TH_CENTRAL.coords,
      VIETNAM_LOCATIONS.TH_SAM_SON.coords,
    ], 6),
  },
];

export const INITIAL_PASSENGERS: PassengerRequest[] = [
  // 1. Perfect Match: Hà Nội -> Ninh Bình (2 seats)
  {
    id: 'PR_01',
    passengerName: 'Nguyễn Thu Trang',
    passengerPhone: '0901 234 567',
    origin: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    destination: VIETNAM_LOCATIONS.NB_CENTRAL,
    departureWindow: { start: '08:00', end: '08:45', date: '2026-08-20' },
    seats: 2,
    rideType: 'shared',
    pickupType: 'meeting_point',
    preferences: { noSmoking: true, quietRide: true },
    status: 'pending',
    createdAt: '2026-08-19T10:00:00Z',
  },

  // 2. High Match (Sub-segment): Hà Nội -> Nam Định (1 seat)
  {
    id: 'PR_02',
    passengerName: 'Phạm Minh Quân',
    passengerPhone: '0912 987 654',
    origin: VIETNAM_LOCATIONS.HN_HOAN_KIEM,
    destination: VIETNAM_LOCATIONS.ND_BIG_C,
    departureWindow: { start: '08:15', end: '09:00', date: '2026-08-20' },
    seats: 1,
    rideType: 'shared',
    pickupType: 'meeting_point',
    preferences: { noSmoking: true },
    status: 'pending',
    createdAt: '2026-08-19T10:05:00Z',
  },

  // 3. Mid-Corridor Boarding: Phủ Lý (Hà Nam) -> Ninh Bình (2 seats)
  {
    id: 'PR_03',
    passengerName: 'Vũ Đức Thịnh',
    passengerPhone: '0933 555 777',
    origin: VIETNAM_LOCATIONS.HNAM_PHU_LY,
    destination: VIETNAM_LOCATIONS.NB_CENTRAL,
    departureWindow: { start: '08:30', end: '09:15', date: '2026-08-20' },
    seats: 2,
    rideType: 'shared',
    pickupType: 'meeting_point',
    preferences: { noSmoking: true },
    status: 'pending',
    createdAt: '2026-08-19T10:10:00Z',
  },

  // 4. Corridor Entry: Hà Nội -> Phủ Lý (1 seat)
  {
    id: 'PR_04',
    passengerName: 'Lê Thảo My',
    passengerPhone: '0987 654 321',
    origin: VIETNAM_LOCATIONS.HN_NUOC_NGAM,
    destination: VIETNAM_LOCATIONS.HNAM_DONG_VAN,
    departureWindow: { start: '08:00', end: '08:30', date: '2026-08-20' },
    seats: 1,
    rideType: 'shared',
    pickupType: 'door_to_door',
    preferences: { noSmoking: true, quietRide: true },
    status: 'pending',
    createdAt: '2026-08-19T10:15:00Z',
  },

  // 5. Door-to-Door Detour: KĐT Văn Quán (Hà Đông) -> Tràng An (Ninh Bình)
  {
    id: 'PR_05',
    passengerName: 'Hoàng Quốc Việt',
    passengerPhone: '0966 888 999',
    origin: VIETNAM_LOCATIONS.HN_HA_DONG,
    destination: VIETNAM_LOCATIONS.NB_TRANG_AN,
    departureWindow: { start: '08:15', end: '08:45', date: '2026-08-20' },
    seats: 2,
    rideType: 'shared',
    pickupType: 'door_to_door',
    preferences: { noSmoking: true, largeTrunk: true },
    status: 'pending',
    createdAt: '2026-08-19T10:20:00Z',
  },

  // 6. WRONG DIRECTION (Hà Nội -> Hải Phòng): MUST BE REJECTED for HN-Ninh Bình drivers
  {
    id: 'PR_06',
    passengerName: 'Trần Hải Đăng',
    passengerPhone: '0909 111 222',
    origin: VIETNAM_LOCATIONS.HN_LONG_BIEN,
    destination: VIETNAM_LOCATIONS.HP_CENTRAL,
    departureWindow: { start: '08:00', end: '08:30', date: '2026-08-20' },
    seats: 2,
    rideType: 'shared',
    pickupType: 'meeting_point',
    preferences: { noSmoking: true },
    status: 'pending',
    createdAt: '2026-08-19T10:25:00Z',
  },

  // 7. INSUFFICIENT SEATS (Requires 4 seats on 2-seat available car): MUST BE REJECTED
  {
    id: 'PR_07',
    passengerName: 'Đoàn Gia Đình (Bao ghế nhóm 4 người)',
    passengerPhone: '0918 333 444',
    origin: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    destination: VIETNAM_LOCATIONS.NB_CENTRAL,
    departureWindow: { start: '08:00', end: '08:30', date: '2026-08-20' },
    seats: 4,
    rideType: 'shared',
    pickupType: 'meeting_point',
    preferences: { noSmoking: true },
    status: 'pending',
    createdAt: '2026-08-19T10:30:00Z',
  },

  // 8. TIME CONFLICT (Evening 18:00 vs Morning 08:00): MUST BE REJECTED
  {
    id: 'PR_08',
    passengerName: 'Bùi Thanh Hương',
    passengerPhone: '0944 666 888',
    origin: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    destination: VIETNAM_LOCATIONS.NB_CENTRAL,
    departureWindow: { start: '18:00', end: '19:00', date: '2026-08-20' },
    seats: 1,
    rideType: 'shared',
    pickupType: 'meeting_point',
    preferences: { noSmoking: true },
    status: 'pending',
    createdAt: '2026-08-19T10:35:00Z',
  },

  // 9. REVERSE DIRECTION (Ninh Bình -> Hà Nội): MUST BE REJECTED for HN->NB drivers
  {
    id: 'PR_09',
    passengerName: 'Đỗ Văn Thành',
    passengerPhone: '0977 444 555',
    origin: VIETNAM_LOCATIONS.NB_CENTRAL,
    destination: VIETNAM_LOCATIONS.HN_GIAP_BAT,
    departureWindow: { start: '08:00', end: '08:30', date: '2026-08-20' },
    seats: 2,
    rideType: 'shared',
    pickupType: 'meeting_point',
    status: 'pending',
    createdAt: '2026-08-19T10:40:00Z',
  },

  // 10. Long corridor extension: Hà Nội -> TP. Thanh Hóa (2 seats)
  {
    id: 'PR_10',
    passengerName: 'Nguyễn Đình Trọng',
    passengerPhone: '0912 777 888',
    origin: VIETNAM_LOCATIONS.HN_NUOC_NGAM,
    destination: VIETNAM_LOCATIONS.TH_CENTRAL,
    departureWindow: { start: '08:00', end: '08:30', date: '2026-08-20' },
    seats: 2,
    rideType: 'shared',
    pickupType: 'meeting_point',
    preferences: { noSmoking: true, largeTrunk: true },
    status: 'pending',
    createdAt: '2026-08-19T10:45:00Z',
  },
];
